### ISSUE TITLE
All Solver Software Engineering Overhaul

### ISSUE THREAD

**Issue by seanebum** [GillesPy2/GillesPy2#112]
Solvers have same code for state initialization, simulation_data output, tau selection, etc.   This should potentially be located in a separate file, so that any update to these methods will update for all solvers.  This will be especially useful for future work such as live data plotting, events, and delays #24 #43 #44

**Comment by seanebum** [comment]
CodeClimate should now provide some guidelines for general engineering improvements

**Comment by Fin109** [comment]
On merge of #347, close this issue
