### ISSUE TITLE
random seeding needs to be uniform (w/ unit test)

### ISSUE THREAD

**Issue by seanebum** [GillesPy2/GillesPy2#146]
Currently, seeding is not implemented on all solvers.

Also, There is a discrepency between the StochSS method of seeding and GillesPy2 method of seeding:

GillesPy2 default seed is None, and will seed if any value is given
StochSS default seed is -1, and will seed if any OTHER value is given

One of these two methods should be selected, and consistently adhered to.

Also, there should be unit tests for each solver ensuring that they are seeding correctly.

**Comment by briandrawert** [comment]
The C solver does not seem to be doing the correct thing with -1 for seed (random seed).  This needs to be confirmed

**Comment by seanebum** [comment]
fixed with #166, close with merge

**Comment by seanebum** [comment]
merging with #172
