### ISSUE TITLE
LacOperon example getting stuck when simulated

### ISSUE THREAD

**Issue by eweisger** [GillesPy2/GillesPy2#179]
The LacOperon Example Model is getting hung up somewhere during simulation and does not provide any error messages. The code being used to run the model is:
lacOperon_model = LacOperon()
results = lacOperon_model.run()

**Comment by briandrawert** [comment]
Try running on the 'enable_timeouts" branch, add "timeout=300" to the run() function.  See if this gives any data back.

**Comment by briandrawert** [comment]
Changed model, fixed issue
