### ISSUE TITLE
NumPySSASolver propensity function error

### ISSUE THREAD

**Issue by georgemhall** [GillesPy2/GillesPy2#22]
# species
        S = gillespy2.Species(name='S', initial_value=init_v)
        A = gillespy2.Species(name='A', initial_value=200)
        H = gillespy2.Species(name='H', initial_value=0)
        
        self.add_species([S,A,H])
        
        # parameters
        k2 = gillespy2.Parameter(name='k2', expression=1e-10)
        k3 = gillespy2.Parameter(name='k3', expression=0.05)
        Sa = gillespy2.Parameter(name='Sa', expression=3e8)
        MuA = gillespy2.Parameter(name='MuA', expression=0.05)

%time results = model.run(solver=NumPySSASolver, show_labels=True)

  File "<string>", line 1
    lambda x:x[0]a*vol
                 ^
SyntaxError: invalid syntax

Note: parameter 'Sa' and species 'S' - search & replace on line 58 is struggling

@briandrawert @Thisisnotdalton

**Comment by Thisisnotdalton** [comment]
#21

**Comment by briandrawert** [comment]
Need to make a test for this.  When that runs, close this issue.

**Comment by Thisisnotdalton** [comment]
This should be fixed with #35.
