### ISSUE TITLE
Need a copyright statement

### ISSUE THREAD

**Issue by mhucka** [GillesPy2/GillesPy2#222]
The GillesPy2 README and other documentation do not seem to have a copyright statement anywhere. What should be the copyright(s)?

(FWIW, my experience has been that the institution that supports the work requires that its members assert a copyright of some kind on software produced while working for the institution. This is usually part of the employee agreements. The software may still be open-source licensed – that's a separate question. Relatedly, my understanding of licensing is that to assert a license – which GillesPy2 already does – one has to have a copyright statement too.)

**Comment by makdl** [comment]
This issue has been resolved by PR #281.
