### ISSUE TITLE
SSACSolver custom propensity does NOT give an overflow error.

### ISSUE THREAD

**Issue by Fin109** [GillesPy2/GillesPy2#273]
When using the GeneticTogglSwitch.ipynb file, one will notice that by altering the propensity_function for the reaction "cu" (try: pow(gamma,pow(2.7,100)) , and using the SSACSolver, the solver will not fail.

By contrast, the NumPySSASolver WILL fail giving: 

"<string> in <lambda>(S)

OverflowError: (34, 'Numerical result out of range')"

**Comment by briandrawert** [comment]
1. Test this with the timeout flag, see if the SSACsolver does timeout correctly.
2.  Investigate if the C++, see how to detect OverflowError
