### ISSUE TITLE
Develop and Master solvers don't work on Windows 

### ISSUE THREAD

**Issue by hodgespodge** [GillesPy2/GillesPy2#300]
Signal creating code for timeouts don't work in windows so you get this error when running any solver (even without timeouts or livegraphing selected)

 def time_out(time):
    609             # Register a function to raise a TimeoutError on the signal.
--> 610             signal.signal(signal.SIGALRM, raise_time_out)
    611             # Schedule the signal to be sent after ``time``.
    612             signal.alarm(time)

**Comment by briandrawert** [comment]
Fixed with #304
