### ISSUE TITLE
numpy.int64 should be recognized as int

### ISSUE THREAD

**Issue by briandrawert** [GillesPy2/GillesPy2#305]
type = <class 'numpy.int64'>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-1d505fd5112a> in <module>
----> 1 model = Spatial_COVID_19()

<ipython-input-34-be319e456a02> in __init__(self, parameter_values)
     55             print(type(pop))
     56 
---> 57             healthy = Species(name='healthy-'+cname, initial_value=pop)
     58             infected = Species(name='infected-'+cname, initial_value=inf)
     59             symptomatic = Species(name='symptomatic-'+cname, initial_value=sump)

/opt/conda/lib/python3.7/site-packages/gillespy2/core/gillespy2.py in __init__(self, name, initial_value, constant, boundary_condition, mode, allow_negative_populations, switch_min, switch_tol)
    735             self.initial_value = np.float(initial_value)
    736         else:
--> 737             if not isinstance(initial_value, int): raise ValueError('Discrete values must be of type int.')
    738             self.initial_value = np.int(initial_value)
    739         if not allow_negative_populations:

ValueError: Discrete values must be of type int.`

**Comment by seanebum** [comment]
Fixed with #310
