### ISSUE TITLE
Need to be able to pause/resume simulation

### ISSUE THREAD

**Issue by briandrawert** [GillesPy2/GillesPy2#328]

**Comment by briandrawert** [comment]
This will likely fix #327

**Comment by Fin109** [comment]
Current implementation idea, step by step:

- Create thread & thread event monitoring keystroke for "pause" of simulation in the thread that is running the simulation

- When pause keystroke is hit, next time simulation runs through a check for event, save results object, and return it to thread, have ability to interact upon it, etc

- When unpause keystroke is hit, run simulation, passing results object

**Comment by briandrawert** [comment]
Note, the keystroke idea will not work inside a Jupyter Notebook.

**Comment by Fin109** [comment]
> Note, the keystroke idea will not work inside a Jupyter Notebook.

Got it, in that case using their pause and have it actually work would be the best option - I see what you mean be the reference to #327. Looking into workarounds now.

**Comment by briandrawert** [comment]
My thought is that "pause" really means stop the simulation unexpectedly, and return the result.  So on the terminal, if you hit Ctl-C it just kills the simulation.  What if it interrupted it, but returned a result anyway (like timeout, but without specifying a time a priori).  Then "resume" could mean starting a simulation by passing in (or keeping an internal reference to) a Result object, and picking up where that object left off.

I am often in the situation where I run a simulation from 0-10, and then re-run the simulation from 0-20 (cause 10 was not long enough).  It would be nice to have the 2nd one start where the 1st one left off (run 10-20)
