### ISSUE TITLE
Modification of the iniatial value of a specie in the run time ?

### ISSUE THREAD

**Issue by odannis** [GillesPy2/GillesPy2#359]
Hi, 

I would like to be able to do model.run(number_of_trajectories=100) and at each simulation the initial value of my species follow a Poisson law. Is it possible ?

The only way i find for the moment, is to do :  model.run(number_of_trajectories=1), to change the initial value with : model.delete_specie and modele.add_specie and to do again  model.run(number_of_trajectories=1). But it seems to take a long time to compile. 

Thank for the good job that you have done and for your help

**Comment by briandrawert** [comment]
Hi odannis,

What you are asking can easily be done with our new VariableSSACSolver.
See: https://github.com/GillesPy2/GillesPy2/blob/master/examples/AdvancedFeatures/Variable%20SSA%20C%20Example.ipynb

For example, if you wanted to change the initial condition of species "A":
```
solver = VariableSSACSolver(model=model)
result = model.run(solver=solver, variables={'A': np.random.poisson(20)})
for i in range(1,10):
    result += model.run(solver=solver, variables={'A': np.random.poisson(15)})
result.plotplotly()
```

**Comment by odannis** [comment]
Thank you for your answer !!

**Comment by odannis** [comment]
Hi,

I would like to do the simulation 10 000 times to compute the probability of a rare event. And i have the impression that using model.run() 10 000 times is less efficient than model.run(number_of_trajectories = 10 000). 
Is it a way to use model.run(number_of_trajectories = 1000) with a new initial value for one variable ?

**Comment by briandrawert** [comment]
Your impression is false.  It is not less efficient to use the code in the way I have written it above.

However, I must warn you that computing rare event probability by direct simulation is both extremely expensive and typically incorrect. I refer you to the rare event SSA paper in the literature for details.

**Comment by odannis** [comment]
Hi,

I have the impression that for your generation of random number you take a lot of time the same seed. 
The variance of the result of the simulation were high with :
output += model.run(solver=solver,  variables={'A': np.random.poisson(15)}))
But when i added :
output += model.run(solver=solver, seed = np.random.randint(1,10000),  variables={'A': np.random.poisson(15)}))

It was way more better ! How do you chose the seed with model.run(solver=solver,  variables={'A': np.random.poisson(15)})) ?

Thank you for your help

**Comment by briandrawert** [comment]
You are correct, thanks for pointing this out.  If no seed is given, the current unix time is used.  This means that for fast repeated invocations of the run() method (within the same second), they will have the same solver.

This #364 PR should fix that.
