### ISSUE TITLE
Pause/Resume Numpy SSA

### ISSUE THREAD

**Issue by hodgespodge** [GillesPy2/GillesPy2#381]
When resuming a numpy ssa simulation, species population reverts to initial values

**Comment by Fin109** [comment]
From our example models, it seems that only the NumPySSASolver and the VariableSSACSolvers do this, on the Michaelis Menten model. The rest of the example models do not display this behavior. Looking into it further.

**Comment by Fin109** [comment]
Close on merge of #387
