### ISSUE TITLE
Trajectory Output Deviation in the new version(1.5.0)

### ISSUE THREAD

**Issue by hemanshudas** [GillesPy2/GillesPy2#391]
While using the new GillesPy2 version, the solver fails at generating the trajectories. I can't explain the issue clearly - but I've attached the output from NumPySSASolver() from the previous 1.4.2 version and the 1.5.0 version. I've used the same exact code for both. I do observe that the first trajectory (#0) is simulated correctly. 

Also, while the previous code took around 5 mins to simulate each model (125 trajectories), the new version takes 2 seconds - so something is amiss. I get the same issue while using BasicTauLeapingSolver() and TauLeapingSolver() in v1.4.2 and v1.5.0 respectively. 

**Plot with v1.5.0**
![Plot_V1 5 0](https://user-images.githubusercontent.com/48236768/86798251-337de880-c08e-11ea-9add-31dc27123f9e.png)

**Plot with v1.4.2**
![Plot_V1 4 2](https://user-images.githubusercontent.com/48236768/86798317-42fd3180-c08e-11ea-92c2-a2a834778479.png)

**Comment by seanebum** [comment]
Hi @hemanshudas, thank you for posting the issue!  We are working to resolve this right now, and I'm sorry for the inconvenience!  I'll let you know as soon as this is resolved!

**Comment by seanebum** [comment]
@hemanshudas, this should be fixed now in the recent changes, please update to v.1.5.1 and let me know if that works!

**Comment by hemanshudas** [comment]
It works perfectly now. My super appreciation for the quick response and the work behind this package.
