### ISSUE TITLE
import gillespy2 sometimes fails if unable to use C solvers

### ISSUE THREAD

**Issue by hodgespodge** [GillesPy2/GillesPy2#392]
> 2020-07-07 11:50:44,488 - root - WARNING - Unable to use C++ optimized SSA: argument 'solver=<class 'gillespy2.solvers.cpp.ssa_c_solver.SSACSolver'>' to run() failed.  Reason Given: buffer size must be a multiple of element size.  The performance of this package can be significantly increased if you install/configure GCC on this machine.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cd8610b65d68> in <module>()
      3 import numpy
      4 sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../../../')))
----> 5 import gillespy2
      6 from gillespy2 import TauLeapingSolver

C:\Users\Samuel Hodges\PycharmProjects\GillesPy2\gillespy2\__init__.py in <module>()
     11 
     12 
---> 13 from gillespy2.solvers import *
     14 from gillespy2.core import *
     15 import gillespy2.sbml

AttributeError: module 'gillespy2.solvers' has no attribute 'SSACSolver'

**Comment by hodgespodge** [comment]
Tested on master branch. Error only happened once and restarting the notebook fixed the problem.

**Comment by Fin109** [comment]
#393 should fix this issue.
