### ISSUE TITLE
Not naming reactions leads to non-deterministic simulations

### ISSUE THREAD

**Issue by matt-graham** [GillesPy2/GillesPy2#409]
When constructing a model in which names are not provided for one or more reactions, calling `model.run` with a `seed` argument set (or correspondingly calling the `run` method of a specific solver) does not give deterministic results when using different model instances but with identical parameters / initial species values.

As a simple example using the `Dimer` model from the README, the following raises an `AssertionError` using `v1.5.1` on Python 3.7, installed using `pip`.

```Python
import gillespy2
import numpy as np

class Dimerization(gillespy2.Model):

    def __init__(self, parameter_values=None):
        gillespy2.Model.__init__(self, name='Dimerization')
        k_c = gillespy2.Parameter(name='k_c', expression=0.005)
        k_d = gillespy2.Parameter(name='k_d', expression=0.08)
        self.add_parameter([k_c, k_d])
        m = gillespy2.Species(name='monomer', initial_value=30)
        d = gillespy2.Species(name='dimer',   initial_value=0)
        self.add_species([m, d])
        r_c = gillespy2.Reaction(rate=k_c, reactants={m:2}, products={d:1})
        r_d = gillespy2.Reaction(rate=k_d, reactants={d:1}, products={m:2})
        self.add_reaction([r_c, r_d])
        self.timespan(np.linspace(0, 100, 101))

seed = 1234
solver = gillespy2.NumPySSASolver()
orig_model = Dimerization()
orig_results, = model.run(solver=solver, seed=seed)

for i in range(100):
    model = Dimerization()
    results, = model.run(solver=solver, seed=seed)
    assert np.allclose(results['dimer'], orig_results['dimer'])
```

This appears to be because when calling `model.add_reactions` with a list of reactions, the list is sorted by the string representations of the reactions (which begins with the reaction name) prior to adding to the `model.listOfReactions` `OrderedDict`, and for reactions in which the name argument is not provided, the name is generated as a random UUID. As these UUIDs differ on each instantiation of the model, the order of the reactions are internally recorded with can differ which gives different simulation results. 

This is easy to rectify just by naming all reactions, but it was not immediately obvious (or at least it wasn't to me!) that not naming the reactions would lead to this behaviour and it took me a while to figure out why I was getting different simulation results when re-running the same script despite fixing the random seed. I could not see this point mentioned anywhere in the documentation - it might be helpful to put a note on the docstring for the `name` argument to the `Reaction` class that although optional this needs to be specified to get deterministic behaviour?

**Comment by seanebum** [comment]
This should be resolved now with GillesPy2 v.1.5.2

**Comment by matt-graham** [comment]
Thanks for the swift fix!
