### ISSUE TITLE
TauHybridSolver errors out

### ISSUE THREAD

**Issue by hemanshudas** [GillesPy2/GillesPy2#415]
Dear Team,
Thanks for the amazing work on the package. It has simplified stochastic epi simulations a lot for me. 

I need a few clarifications on the TauHybridSolver. I'm using it to incorporate events in the model.

1. The code works fine with TauLeapingSolver, but it is without events. Events are compatible with the HybridSolver only, right?
2. The code errors out for the 10th trajectory with the below error. How could I understand what I'm doing wrong. 
3. What does the 'ts' variable capture. I'm unclear on that. 

Thanks for the help.
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/gillespy2/core/model.py in run(self, solver, timeout, t, show_labels, cpp_support, **solver_args)
>     800             solver_results, rc = solver.run(model=self, t=t, increment=self.tspan[-1] - self.tspan[-2],
> --> 801                                             timeout=timeout, **solver_args)
>     802         except Exception as e:
> 
> 8 frames
> **ValueError: `ts` must be strictly increasing or decreasing.**
> 
> During handling of the above exception, another exception occurred:
> 
> SimulationError                           Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/gillespy2/core/model.py in run(self, solver, timeout, t, show_labels, cpp_support, **solver_args)
>     811                                 " run properly.")
>     812             raise SimulationError(
> --> 813                 "argument 'solver={}' to run() failed.  Reason Given: {}".format(solver, e))
>     814 
>     815         if rc == 33:
> 
> SimulationError: argument 'solver=<gillespy2.solvers.numpy.tau_hybrid_solver.TauHybridSolver object at 0x7f076b544eb8>' to run() failed.  **Reason Given: `ts` must be strictly increasing or decreasing.**

**Comment by seanebum** [comment]
Hi @hemanshudas,

1.  That is correct, events are only compatible with the hybrid solver (presently).
2.  I don't think you are doing anything wrong, but would you be able to share the model that produces this issue for troubleshooting/testing?
3. The 'ts' variable is an internal variable used for dense output interpolation with the scipy.integrate.solve_ivp ode solver which gillespy2 uses in the hybrid solver.

Thanks!

**Comment by hemanshudas** [comment]
Thanks. You can access my code [here](https://colab.research.google.com/drive/1FVQds7DcvOvoFIqvPJkVWuyGXKAQbFW0?usp=sharing). 

There are many species and reactions - so I'm not sure if it'll be easy to decode. But you could surely test on it. Happy to walk you through it if required.

Also, I'm not sure how the first 9 trajectories simulate without issue but the 10th trajectory fails.

**Comment by seanebum** [comment]
@hemanshudas 

This issue should be resolved now as of v.1.5.3.  The model you shared ran successfully for me on the new version, let me know if you encounter any more issues!
