### ISSUE TITLE
Import from StochML

### ISSUE THREAD

**Issue by rmjiang7** [GillesPy2/GillesPy2#420]
I'm trying to import and run a model written in StochML (https://github.com/StochSS/StochKit/blob/master/models/examples/heat_shock_mixed.xml) but I'm running into a couple of issues.

1.  The model can be run using the NumPySSASolver and the SSACSolver but the results don't seem to match up at all, even accounting for stochasticity (the NumPy version is expected to take a long time).  I'm not sure what the cause of the problem is but the numpy version appears to be the correct one.  

2.  The ODESolver does not seem to work at all.  Upon further inspection, it seems like the `reaction.ode_propensity_function` returns None for all reactions.  

Here is the code that I was running

```
import gillespy2
from gillespy2.solvers import ODESolver, SSACSolver, NumPySSASolver

heat_shock = gillespy2.StochMLDocument.from_file("heat_shock_mixed.xml").to_model("heat_shock")
heat_shock.timespan(np.linspace(0, 2, 10))
res_ode = heat_shock.run(solver = ODESolver) # doesn't work
res_ssa = heat_shock.run(solver = SSACSolver) # works (but wrong solution?)
res_ssa_np = heat_shock.run(solver = NumPySSASolver) # works
```

**Comment by seanebum** [comment]
Fixed with #424
