### ISSUE TITLE
StochSS MDL Export

### ISSUE THREAD

**Issue by rmjiang7** [GillesPy2/GillesPy2#428]
Currently, there is no way to export a model written in gillespy2 for import into StochSS.  This would be useful for leveraging the user interface/analysis tools available in StochSS as well as for sharing models among a broader team.

**Comment by briandrawert** [comment]
Idea: StochSS can import a pickle file and convert it to a MDL file.  That way all code related the the MDL format.  https://github.com/StochSS/stochss/issues/995
