### ISSUE TITLE
Using legend to turn off a species only turns off one trace when plotting multiple trajectories in one plot

### ISSUE THREAD

**Issue by BryanRumsey** [GillesPy2/GillesPy2#429]
![plot_with_B_turned_off](https://user-images.githubusercontent.com/44621966/90658316-6f6da700-e211-11ea-8e3f-b25e60195d3b.png)
![plot_without_modification](https://user-images.githubusercontent.com/44621966/90658318-709ed400-e211-11ea-9533-263ab150b6e4.png)

**Comment by Fin109** [comment]
Close on merge of #431

**Comment by seanebum** [comment]
Fixed with #431
