### ISSUE TITLE
Remove BasicSSASolver

### ISSUE THREAD

**Issue by briandrawert** [GillesPy2/GillesPy2#57]

**Comment by georgemhall** [comment]
gillespy2\solvers\auto\ssa_solver.py still contains a reference to the BasicSSASolver which I see has been removed from the develop branch.

I changed the default to the NumPy SSA solver in my travis-testing-fix branch which I will create a PR for soon, but I wanted to notify everyone
@briandrawert @seanebum @Thisisnotdalton

**Comment by seanebum** [comment]
Good catch on that, thank you!
