### ISSUE TITLE
Adding a dictionary of reactions raises a ModelError

### ISSUE THREAD

**Issue by Aratz** [GillesPy2/GillesPy2#85]
When providing `add_reaction` with a dictionary of reactions, a `ModelError` is raised (see example code below).

        model = Model()
        rate = Parameter(name='rate', expression=0.5)
        model.add_parameter(rate)
        species1 = Species('A', initial_value=0)
        species2 = Species('B', initial_value=0)
        model.add_species([species1, species2])
        reactions = {
                name: Reaction(
                    name=name, 
                    reactants={species1: 1}, products={species2: 1}, rate=rate)
                for name in ["reaction1", "reaction2"]}
        model.add_reaction(reactions) # Raises ModelError

This is because `reactions.values` returns `dict_values` object instead of a `list` (see line 347 in `core/gillespy2.py`).

**Comment by briandrawert** [comment]
Thanks @Aratz!
